### ISSUE TITLE
HP 3PAR Storage Infosight Registraytion- HPE Support Case 5353276399 

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Storage#4]
Dear Praveen Kumar, 

Thank you for contacting Hewlett Packard Enterprise for your service needs. This email confirms that your request for service has been created as follows: 
Case Reference ID: 5353276399 
Status: Case is generated and in Progress 
Subject: HPE 3PAR StoreServ 8200 2-node Field Integrated Storage Base - Infosight details
Product: HPE 3PAR StoreServ 8200 2-node Field Integrated Storage Base 
Product number: K2Q36A 
Serial number: 7CE641P1JN 

Call is registered in HPE for registered HP 3PAR Storage in Infosight

@Isgec/dc-infra-team  ,Myself Praveen Kumar is working with HP Support Team for the same.

**Comment by vinay-isgec** [comment]
Hi Team,

 

Please see the attached mail for reference.

 

In attached mail  below message is written 

“This is regarding the Infosight registration for array SN: 7CE641P1JN

We see that array is not registered for Infosight below are details about Infosight and steps to register for Infosight” Etc….

 

Please do the needful for above mentioned issue.



 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: HPE Case Management System [mailto:gsd_csc_case_mngmt@hpe.com] 
Sent: 02 February 2021 11:07
To: emailsupport@isgec.co.in
Cc: gscbindia.swd@hpe.com; radhika.n@hpe.com
Subject: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hello Team,
 
"GREETINGS FROM HPE"
 
We are pleased to assist you on the issue being faced.
We understand that you have received an alert for this unit.

As discussed, Kindly share us the alert details and screenshots.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com 
If you need urgent support over the phone please find the support options: 
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager  <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,q5OBj4SZiDoBrAOgPRVmScqW4x70cDdk4YrJDvhwUGJWFvXfAN6ZpKdniG2O368aazj-FF86Y409NP0xH_WSi0hH2o8ls8TcOtQB0Rc4EnAQhCSYcIO4Fq4,&typo=1> 

   <https://hp.my.salesforce.com/servlet/servlet.ImageServer?oid=00Dd0000000bUlK&esid=0181V00000SnWPj&from=ext> 

ref:_00Dd0bUlK._5001V1AAHLr:ref

**Comment by vinay-isgec** [comment]
Hello Praveen,

Thank you sharing the details.

As we see, email has been sent from HPE team.
Kindly share details with the array serial number and array details.

We have added Infosight email ID on this email.
Also please do reach out/ revert back to the same email.


Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>
Feedback to my manager – Devashish Banerjee - devashish.banerjee@hpe.com<mailto:devashish.banerjee@hpe.com>
If you need urgent support over the phone please find the support options:
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager<https://h20566.www2.hpe.com/portal/site/hpsc/public/scm/home?ac.admitted=1470780193089.125225703.1938120508>

From: Praveen Kumar <praveen1.kumar@isgec.co.in>
Sent: Tuesday, February 2, 2021 12:00 PM
To: HPE Case Management System <gsd_csc_case_mngmt@hpe.com>
Cc: GRS INDIA Storage <gscbindia.swd@hpe.com>; N, Radhika <radhika.n@hpe.com>; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hi Team,

Please see the attached mail for reference.

In attached mail  below message is written
“This is regarding the Infosight registration for array SN: 7CE641P1JN

We see that array is not registered for Infosight below are details about Infosight and steps to register for Infosight” Etc….

Please do the needful for above mentioned issue.

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.
Regards.....
Praveen (SYSTEMS)
[cid:image001.png@01D6F968.D1D4D670]
A-8, Sector- 63, Noida, UP
Email: praveen1.kumar@isgec.co.in
website: www.isgec.com<http://www.isgec.com>
Mobile:  +91 8448595785

From: HPE Case Management System [mailto:gsd_csc_case_mngmt@hpe.com]
Sent: 02 February 2021 11:07
To: emailsupport@isgec.co.in
Cc: gscbindia.swd@hpe.com; radhika.n@hpe.com
Subject: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hello Team,

"GREETINGS FROM HPE"

We are pleased to assist you on the issue being faced.
We understand that you have received an alert for this unit.

As discussed, Kindly share us the alert details and screenshots.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>
If you need urgent support over the phone please find the support options:
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,q5OBj4SZiDoBrAOgPRVmScqW4x70cDdk4YrJDvhwUGJWFvXfAN6ZpKdniG2O368aazj-FF86Y409NP0xH_WSi0hH2o8ls8TcOtQB0Rc4EnAQhCSYcIO4Fq4,&typo=1>

 [Image removed by sender.]

ref:_00Dd0bUlK._5001V1AAHLr:ref

**Comment by vinay-isgec** [comment]
Hi Team,

 

Please find the Detail:

Array Serial Number:     7CE641P1JN

Email ID:                               emailsupport@isgec.co.in

 

I also share the output of “showsys –d” command below. Please check                 , If you require any more details please inform.

 

 

 

ISGEC_3PAR01 cli% showsys -d

---------------General---------------

System Name         :    ISGEC_3PAR01

System Model        :   HPE_3PAR 8200

Serial Number       :      7CE641P1JN

System ID           :         0x1BE3E

Number of Nodes     :               2

Master Node         :               1

Nodes Online        :             0,1

Nodes in Cluster    :             0,1

Cluster LED         :             Off

Chunklet Size (MiB) :            1024

Minimum PW length   :               6

 

-----System Capacity (MiB)-----

Total Capacity     :   35893248

Allocated Capacity :    8115200

Free Capacity      :   27778048

Failed Capacity    :          0

 

-----Remote_Syslog_Status------

Active              :         0

General Server      :   0.0.0.0

General Connection  :      None

Security Server     :   0.0.0.0

Security Connection :      None

 

--------System Descriptors--------

Location    : A-4 Sector-24, Noida, Uttar Pradesh, 201301, IN

Owner       :

Contact     : Praveen Kumar

Comment     :

 

ISGEC_3PAR01 cli%

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: N, Radhika [mailto:radhika.n@hpe.com] 
Sent: 02 February 2021 13:39
To: Praveen Kumar; HPE Case Management System; HPE_InfoSight_Portal_Support@groups.ext.hpe.com
Cc: GRS INDIA Storage; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hello Praveen,

 

Thank you sharing the details.

 

As we see, email has been sent from HPE team.

Kindly share details with the array serial number and array details.

 

We have added Infosight email ID on this email.

Also please do reach out/ revert back to the same email.

 

 

Regards,

Radhika N

Technical Solutions Consultant

Hewlett Packard Enterprise

Working Days: Mon - Fri 8:00-17:00 IST

Team PDL – gscbindia.swd@hpe.com 

Feedback to my manager – Devashish Banerjee - devashish.banerjee@hpe.com

If you need urgent support over the phone please find the support options: 

STD Support       1800 419 8080

24x7 Support      1800 419 4994

You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,AVOEaZp8ErpoM9ggWOD90tvotgPQJYo9r2od1ue-wZaVKB1gtUr1NUATp3iOBe-xzPVetvFHhe8RQ7WsmWH2-Z6MhiCV00lOoLmu84tQ7XmAn9yxp8uxnlG4MQ,,&typo=1>  

 

From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: Tuesday, February 2, 2021 12:00 PM
To: HPE Case Management System <gsd_csc_case_mngmt@hpe.com>
Cc: GRS INDIA Storage <gscbindia.swd@hpe.com>; N, Radhika <radhika.n@hpe.com>; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hi Team,

 

Please see the attached mail for reference.

 

In attached mail  below message is written 

“This is regarding the Infosight registration for array SN: 7CE641P1JN

We see that array is not registered for Infosight below are details about Infosight and steps to register for Infosight” Etc….

 

Please do the needful for above mentioned issue.

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com <https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com&c=E,1,eTTvW71aMPQGzR6DgItd69VqpDKpiF2zlVpC6zfjALKRIdKd3G8bVY4zPQLwQT5tyFCpy2diagdaingAnYQ9kJMat9UEj7Y5L_EdlLD5uEyfRz70&typo=1> 

Mobile:  +91 8448595785

 

From: HPE Case Management System [mailto:gsd_csc_case_mngmt@hpe.com] 
Sent: 02 February 2021 11:07
To: emailsupport@isgec.co.in
Cc: gscbindia.swd@hpe.com; radhika.n@hpe.com
Subject: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hello Team,
 
"GREETINGS FROM HPE"
 
We are pleased to assist you on the issue being faced.
We understand that you have received an alert for this unit.

As discussed, Kindly share us the alert details and screenshots.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com 
If you need urgent support over the phone please find the support options: 
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager  <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,q5OBj4SZiDoBrAOgPRVmScqW4x70cDdk4YrJDvhwUGJWFvXfAN6ZpKdniG2O368aazj-FF86Y409NP0xH_WSi0hH2o8ls8TcOtQB0Rc4EnAQhCSYcIO4Fq4,&typo=1> 

 Image removed by sender.

ref:_00Dd0bUlK._5001V1AAHLr:ref

**Comment by vinay-isgec** [comment]
Hi Team,

 

Still we are waiting of your reply. Please do the needful as soon as possible.

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: 02 February 2021 17:53
To: 'N, Radhika'; 'HPE Case Management System'; HPE_InfoSight_Portal_Support@groups.ext.hpe.com
Cc: 'GRS INDIA Storage'; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hi Team,

 

Please find the Detail:

Array Serial Number:     7CE641P1JN

Email ID:                               emailsupport@isgec.co.in

 

I also share the output of “showsys –d” command below. Please check                 , If you require any more details please inform.

 

 

 

ISGEC_3PAR01 cli% showsys -d

---------------General---------------

System Name         :    ISGEC_3PAR01

System Model        :   HPE_3PAR 8200

Serial Number       :      7CE641P1JN

System ID           :         0x1BE3E

Number of Nodes     :               2

Master Node         :               1

Nodes Online        :             0,1

Nodes in Cluster    :             0,1

Cluster LED         :             Off

Chunklet Size (MiB) :            1024

Minimum PW length   :               6

 

-----System Capacity (MiB)-----

Total Capacity     :   35893248

Allocated Capacity :    8115200

Free Capacity      :   27778048

Failed Capacity    :          0

 

-----Remote_Syslog_Status------

Active              :         0

General Server      :   0.0.0.0

General Connection  :      None

Security Server     :   0.0.0.0

Security Connection :      None

 

--------System Descriptors--------

Location    : A-4 Sector-24, Noida, Uttar Pradesh, 201301, IN

Owner       :

Contact     : Praveen Kumar

Comment     :

 

ISGEC_3PAR01 cli%

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: N, Radhika [mailto:radhika.n@hpe.com] 
Sent: 02 February 2021 13:39
To: Praveen Kumar; HPE Case Management System; HPE_InfoSight_Portal_Support@groups.ext.hpe.com
Cc: GRS INDIA Storage; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hello Praveen,

 

Thank you sharing the details.

 

As we see, email has been sent from HPE team.

Kindly share details with the array serial number and array details.

 

We have added Infosight email ID on this email.

Also please do reach out/ revert back to the same email.

 

 

Regards,

Radhika N

Technical Solutions Consultant

Hewlett Packard Enterprise

Working Days: Mon - Fri 8:00-17:00 IST

Team PDL – gscbindia.swd@hpe.com 

Feedback to my manager – Devashish Banerjee - devashish.banerjee@hpe.com

If you need urgent support over the phone please find the support options: 

STD Support       1800 419 8080

24x7 Support      1800 419 4994

You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,AVOEaZp8ErpoM9ggWOD90tvotgPQJYo9r2od1ue-wZaVKB1gtUr1NUATp3iOBe-xzPVetvFHhe8RQ7WsmWH2-Z6MhiCV00lOoLmu84tQ7XmAn9yxp8uxnlG4MQ,,&typo=1>  

 

From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: Tuesday, February 2, 2021 12:00 PM
To: HPE Case Management System <gsd_csc_case_mngmt@hpe.com>
Cc: GRS INDIA Storage <gscbindia.swd@hpe.com>; N, Radhika <radhika.n@hpe.com>; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hi Team,

 

Please see the attached mail for reference.

 

In attached mail  below message is written 

“This is regarding the Infosight registration for array SN: 7CE641P1JN

We see that array is not registered for Infosight below are details about Infosight and steps to register for Infosight” Etc….

 

Please do the needful for above mentioned issue.

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com <https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com&c=E,1,eTTvW71aMPQGzR6DgItd69VqpDKpiF2zlVpC6zfjALKRIdKd3G8bVY4zPQLwQT5tyFCpy2diagdaingAnYQ9kJMat9UEj7Y5L_EdlLD5uEyfRz70&typo=1> 

Mobile:  +91 8448595785

 

From: HPE Case Management System [mailto:gsd_csc_case_mngmt@hpe.com] 
Sent: 02 February 2021 11:07
To: emailsupport@isgec.co.in
Cc: gscbindia.swd@hpe.com; radhika.n@hpe.com
Subject: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

 

Hello Team,
 
"GREETINGS FROM HPE"
 
We are pleased to assist you on the issue being faced.
We understand that you have received an alert for this unit.

As discussed, Kindly share us the alert details and screenshots.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com 
If you need urgent support over the phone please find the support options: 
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager  <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,q5OBj4SZiDoBrAOgPRVmScqW4x70cDdk4YrJDvhwUGJWFvXfAN6ZpKdniG2O368aazj-FF86Y409NP0xH_WSi0hH2o8ls8TcOtQB0Rc4EnAQhCSYcIO4Fq4,&typo=1> 

 Image removed by sender.

ref:_00Dd0bUlK._5001V1AAHLr:ref

**Comment by vinay-isgec** [comment]
Hello Praveen,

Thank you for your time on call earlier this morning.

As discussed, Kindly get in touch with the team and they shall assist you on adding array in InfoSight.

We have proceeded this case for closure as we are from breakfix support and adding the array on Infosight is out of scope for us.

Thank you for understanding and your patience on this case.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>
Feedback to my manager – Devashish Banerjee - devashish.banerjee@hpe.com<mailto:devashish.banerjee@hpe.com>
If you need urgent support over the phone please find the support options:
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager<https://h20566.www2.hpe.com/portal/site/hpsc/public/scm/home?ac.admitted=1470780193089.125225703.1938120508>

From: Praveen Kumar <praveen1.kumar@isgec.co.in>
Sent: Tuesday, February 9, 2021 9:54 AM
To: N, Radhika <radhika.n@hpe.com>; HPE Case Management System <gsd_csc_case_mngmt@hpe.com>; HPE_InfoSight_Portal_Support@groups.ext.hpe.com
Cc: GRS INDIA Storage <gscbindia.swd@hpe.com>; reply@reply.github.com; dhirendra.singh@isgec.co.in; emailsupport@isgec.co.in
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hi Team,

Still we are waiting of your reply. Please do the needful as soon as possible.

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.
Regards.....
Praveen (SYSTEMS)
[cid:image001.png@01D6FF1E.C0941400]
A-8, Sector- 63, Noida, UP
Email: praveen1.kumar@isgec.co.in<mailto:praveen1.kumar@isgec.co.in>
website: www.isgec.com<http://www.isgec.com>
Mobile:  +91 8448595785

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in]
Sent: 02 February 2021 17:53
To: 'N, Radhika'; 'HPE Case Management System'; HPE_InfoSight_Portal_Support@groups.ext.hpe.com<mailto:HPE_InfoSight_Portal_Support@groups.ext.hpe.com>
Cc: 'GRS INDIA Storage'; reply@reply.github.com<mailto:reply@reply.github.com>; dhirendra.singh@isgec.co.in<mailto:dhirendra.singh@isgec.co.in>; emailsupport@isgec.co.in<mailto:emailsupport@isgec.co.in>
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hi Team,

Please find the Detail:
Array Serial Number:     7CE641P1JN
Email ID:                               emailsupport@isgec.co.in<mailto:emailsupport@isgec.co.in>

I also share the output of “showsys –d” command below. Please check                 , If you require any more details please inform.



ISGEC_3PAR01 cli% showsys -d
---------------General---------------
System Name         :    ISGEC_3PAR01
System Model        :   HPE_3PAR 8200
Serial Number       :      7CE641P1JN
System ID           :         0x1BE3E
Number of Nodes     :               2
Master Node         :               1
Nodes Online        :             0,1
Nodes in Cluster    :             0,1
Cluster LED         :             Off
Chunklet Size (MiB) :            1024
Minimum PW length   :               6

-----System Capacity (MiB)-----
Total Capacity     :   35893248
Allocated Capacity :    8115200
Free Capacity      :   27778048
Failed Capacity    :          0

-----Remote_Syslog_Status------
Active              :         0
General Server      :   0.0.0.0
General Connection  :      None
Security Server     :   0.0.0.0
Security Connection :      None

--------System Descriptors--------
Location    : A-4 Sector-24, Noida, Uttar Pradesh, 201301, IN
Owner       :
Contact     : Praveen Kumar
Comment     :

ISGEC_3PAR01 cli%
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.
Regards.....
Praveen (SYSTEMS)
[cid:image001.png@01D6FF1E.C0941400]
A-8, Sector- 63, Noida, UP
Email: praveen1.kumar@isgec.co.in<mailto:praveen1.kumar@isgec.co.in>
website: www.isgec.com<http://www.isgec.com>
Mobile:  +91 8448595785

From: N, Radhika [mailto:radhika.n@hpe.com]
Sent: 02 February 2021 13:39
To: Praveen Kumar; HPE Case Management System; HPE_InfoSight_Portal_Support@groups.ext.hpe.com<mailto:HPE_InfoSight_Portal_Support@groups.ext.hpe.com>
Cc: GRS INDIA Storage; reply@reply.github.com<mailto:reply@reply.github.com>; dhirendra.singh@isgec.co.in<mailto:dhirendra.singh@isgec.co.in>; emailsupport@isgec.co.in<mailto:emailsupport@isgec.co.in>
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hello Praveen,

Thank you sharing the details.

As we see, email has been sent from HPE team.
Kindly share details with the array serial number and array details.

We have added Infosight email ID on this email.
Also please do reach out/ revert back to the same email.


Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>
Feedback to my manager – Devashish Banerjee - devashish.banerjee@hpe.com<mailto:devashish.banerjee@hpe.com>
If you need urgent support over the phone please find the support options:
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,AVOEaZp8ErpoM9ggWOD90tvotgPQJYo9r2od1ue-wZaVKB1gtUr1NUATp3iOBe-xzPVetvFHhe8RQ7WsmWH2-Z6MhiCV00lOoLmu84tQ7XmAn9yxp8uxnlG4MQ,,&typo=1>

From: Praveen Kumar <praveen1.kumar@isgec.co.in<mailto:praveen1.kumar@isgec.co.in>>
Sent: Tuesday, February 2, 2021 12:00 PM
To: HPE Case Management System <gsd_csc_case_mngmt@hpe.com<mailto:gsd_csc_case_mngmt@hpe.com>>
Cc: GRS INDIA Storage <gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>>; N, Radhika <radhika.n@hpe.com<mailto:radhika.n@hpe.com>>; reply@reply.github.com<mailto:reply@reply.github.com>; dhirendra.singh@isgec.co.in<mailto:dhirendra.singh@isgec.co.in>; emailsupport@isgec.co.in<mailto:emailsupport@isgec.co.in>
Subject: RE: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hi Team,

Please see the attached mail for reference.

In attached mail  below message is written
“This is regarding the Infosight registration for array SN: 7CE641P1JN

We see that array is not registered for Infosight below are details about Infosight and steps to register for Infosight” Etc….

Please do the needful for above mentioned issue.

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.
Regards.....
Praveen (SYSTEMS)
[cid:image001.png@01D6FF1E.C0941400]
A-8, Sector- 63, Noida, UP
Email: praveen1.kumar@isgec.co.in<mailto:praveen1.kumar@isgec.co.in>
website: www.isgec.com<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com&c=E,1,eTTvW71aMPQGzR6DgItd69VqpDKpiF2zlVpC6zfjALKRIdKd3G8bVY4zPQLwQT5tyFCpy2diagdaingAnYQ9kJMat9UEj7Y5L_EdlLD5uEyfRz70&typo=1>
Mobile:  +91 8448595785

From: HPE Case Management System [mailto:gsd_csc_case_mngmt@hpe.com]
Sent: 02 February 2021 11:07
To: emailsupport@isgec.co.in<mailto:emailsupport@isgec.co.in>
Cc: gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>; radhika.n@hpe.com<mailto:radhika.n@hpe.com>
Subject: HPE Support Case 5353276399 [ ref:_00Dd0bUlK._5001V1AAHLr:ref ]

Hello Team,

"GREETINGS FROM HPE"

We are pleased to assist you on the issue being faced.
We understand that you have received an alert for this unit.

As discussed, Kindly share us the alert details and screenshots.

Regards,
Radhika N
Technical Solutions Consultant
Hewlett Packard Enterprise
Working Days: Mon - Fri 8:00-17:00 IST
Team PDL – gscbindia.swd@hpe.com<mailto:gscbindia.swd@hpe.com>
If you need urgent support over the phone please find the support options:
STD Support       1800 419 8080
24x7 Support      1800 419 4994
You can also log a new case, check the status / update details or raise a call back request on an existing case using the link provided :HPE Support Case Manager <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh20566.www2.hpe.com%2fportal%2fsite%2fhpsc%2fpublic%2fscm%2fhome%3fac.admitted%3d1470780193089.125225703.1938120508&c=E,1,q5OBj4SZiDoBrAOgPRVmScqW4x70cDdk4YrJDvhwUGJWFvXfAN6ZpKdniG2O368aazj-FF86Y409NP0xH_WSi0hH2o8ls8TcOtQB0Rc4EnAQhCSYcIO4Fq4,&typo=1>

 [Image removed by sender.]

ref:_00Dd0bUlK._5001V1AAHLr:ref

**Comment by praveen-isgec** [comment]
HPE Confirmed that Infosight Registration is already done for the same. 

@dhirendra-isgec  , DSB Please close this case.
