### ISSUE TITLE
NetAPP 2554(Sec-63) Storage FC port issue

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Storage#8]
NetApp FAS 2554 (Sec-63) Storage having FC port issue not detecting.

@Isgec/dc-infra-team  , Myself Praveen Kumar is working with Vender to resolve the issue.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: Wednesday, March 10, 2021 9:32 AM
To: Isgec/ITIL-Storage
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Storage] NetAPP 2554(Sec-63) Storage FC port issue (#8)

 

NetApp FAS 2554 (Sec-63) Storage having FC port issue not detecting.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumar is working with Vender to resolve the issue.

**Comment by praveen-isgec** [comment]
Hi Mr. Lovnish,

 

Thanks for your support..

 

We are in under process to replace SFP module, we will inform you when
replace it.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Lovnish Rohewal [mailto:lovnish@evantageit.com] 
Sent: 09 March 2021 19:47
To: 'Praveen Kumar'
Cc: 'Dhirendra Singh Bisht'; bhupender.kashyap@isgec.co.in; 'DCADMIN';
'Vinay Sharma'; 'NGC-akshit-evantageit.com'
Subject: RE: NetAPP Storage FC port issue

 

Dear Mr. Praveen,

 

Activity completed successfully, now port 0e of controller1 is up and
working fine, kindly replace SFP module of 0e controller2. 

 

Please inform me once you replaced, I will check the status after SFP
replacement.

 

Thanks and Regards,

Lovnish Rohewal

+91-9891808001

 

From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: Tuesday, March 09, 2021 3:54 PM
To: 'NGC-lovnish-evantageit.com
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fNGC-lovnish-evantageit.
com&c=E,1,-H5s4TZLCKhFBf4GPNJpyMrJr_SrgvNaxh0c3wJKG-j_xi5VpTMp2r-m4iVxFlYe_4
760FNFEA-OCVWuexo_1gWulPAp7cbF-Eq7-lF33dUTBhxNY3f0AaZy&typo=1&ancr_add=1> '
<lovnish@evantageit.com>
Cc: 'Dhirendra Singh Bisht' <dhirendra.singh@isgec.co.in>;
bhupender.kashyap@isgec.co.in; 'DCADMIN' <dcadmin@isgec.co.in>; 'Vinay
Sharma' <vinay.sharma@isgec.co.in>; 'NGC-akshit-evantageit.com
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fNGC-akshit-evantageit.c
om&c=E,1,6Tpp8OlXBgv798HqdWoYUQIZTQKiOyJ43aswv_zaOnuuBVFm4P1qnsRC91tRzjAoCgh
ipxEfstNjcKqP5UKYCsY0xIEAhvhFGWytPskDEQ,,&typo=1&ancr_add=1> '
<akshit@evantageit.com>
Subject: NetAPP Storage FC port issue

 

Dear Mr. Lovnish,

 

As discussed please make schedule at 06:30PM.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com&c=E,1,6Z3q
0WBs2JponQQHIlN4P6Cx0p1N6DGwQ6r9e2VXrgY8qcLs66QxT32zuqYha6k-nLqmgFZagE3Fzr5G
8_nBZxUxraz9Ub4EW7YAqZkAzimWQHLh_Zaq7ss,&typo=1> 

Mobile:  +91 8448595785

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: 09 March 2021 11:35
To: 'DCADMIN'; 'Vinay Sharma'; 'bhupender.kashyap@isgec.co.in'
Cc: 'Dhirendra Singh Bisht'
Subject: NetApp Storage is schedule restart at 06:30PM today

 

Dear All,

 

We are going to schedule restart NetApp Storage (Sector-63) at 06:30 PM
today.

 

This is for your information.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com&c=E,1,L-Ig
5_72Z81WgX_NuSbwPLw8rVC59LM5bgboo56Wgh2bjdRKQtXqKClleIb9s9fNfFADmLna0tbfTjpX
tA6oinPheaMuKozSE1xR-NO29yl2f2vE3BeP&typo=1> 

Mobile:  +91 8448595785

**Comment by praveen-isgec** [comment]
After Restart Storage all FC Modules are working fine.

@dhirendra-isgec   , DSB Please close this case.
