### ISSUE TITLE
Space provisioning from HP 3PAR for Live Mail Server 192.9.200.224 4.5TB

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Storage#9]
Require 4.5TB Virtual Volume for Live Mail Server 192.9.200.224 for copy all data from existing LUN (NetApp) to this New Virtual Volume.

@Isgec/dc-infra-team  , Myself Praveen Kumar , Mr. MS Ji and Mr. Bhupender Ji are working for this activity.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: Friday, March 19, 2021 4:49 PM
To: Isgec/ITIL-Storage
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Storage] Space provisioning from HP 3PAR for Live Mail Server 192.9.200.224 4.5TB (#9)

 

Require 4.5TB Virtual Volume for Live Mail Server 192.9.200.224 for copy all data from existing LUN (NetApp) to this New Virtual Volume.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumar , Mr. MS Ji and Mr. Bhupender Ji are working for this activity.

**Comment by praveen-isgec** [comment]
4.5 TB Virtual Volume is created on HP 3PAR storage with full provisioning and assigned to EXSi.
